"""PDF export helpers for Inventory and Catalog lists using reportlab."""
import io
import os

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, Flowable, KeepTogether, HRFlowable
)


def _brand_header(doc, brand_title):
    """Return flowable header block with logo + title (best-effort)."""
    from reportlab.platypus import Table as T
    logo_path = os.path.join("static", "logo.jpg")
    parts = []
    logo_cell = None
    if os.path.exists(logo_path):
        try:
            logo_cell = Image(logo_path, width=18 * mm, height=18 * mm, hAlign="LEFT")
        except Exception:
            logo_cell = None

    cell = []
    title = Paragraph(f"<b>{brand_title}</b>", ParagraphStyle(
        "brandTitle", fontName="Helvetica-Bold", fontSize=20, leading=24,
        textColor=colors.HexColor("#1e293b")
    ))
    sub = Paragraph("CRM · Export", ParagraphStyle(
        "brandSub", fontName="Helvetica", fontSize=10, leading=13,
        textColor=colors.HexColor("#64748b")
    ))
    cell.append(title)
    cell.append(sub)

    data_row = []
    if logo_cell is not None:
        data_row.append([logo_cell, cell])
        widths = [22 * mm, None]
    else:
        data_row.append([cell])
        widths = [None]

    t = T(data_row, colWidths=widths)
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
    ]))
    parts.append(t)
    parts.append(Spacer(1, 6 * mm))
    parts.append(_hr())
    parts.append(Spacer(1, 4 * mm))
    return parts


def _hr():
    from reportlab.platypus import HRFlowable
    return HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0"))


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#94a3b8"))
    canvas.drawString(10 * mm, 8 * mm, "Generated by SCM BPO CRM")
    canvas.drawRightString(A4[0] - 10 * mm, 8 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _build_pdf(title, headers, rows, widths):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=landscape(A4),
        leftMargin=12 * mm, rightMargin=12 * mm,
        topMargin=12 * mm, bottomMargin=14 * mm,
    )
    styles = getSampleStyleSheet()

    story = _brand_header(doc, title)

    header_style = ParagraphStyle(
        "hdr", parent=styles["Heading2"], fontSize=15, leading=19,
        textColor=colors.HexColor("#0f172a"), spaceBefore=2, spaceAfter=2
    )
    body_style = ParagraphStyle(
        "body", parent=styles["BodyText"], fontSize=8.5, leading=11,
        textColor=colors.HexColor("#334155"), spaceBefore=0, spaceAfter=0,
        wordWrap="CJK"
    )
    cell_style = ParagraphStyle(
        "cell", parent=body_style, alignment=TA_LEFT
    )

    story.append(Paragraph(title, header_style))
    story.append(Spacer(1, 3 * mm))

    table_data = [[Paragraph(f"<b>{h}</b>", ParagraphStyle(
        "th", parent=body_style, textColor=colors.white,
        fontName="Helvetica-Bold", alignment=TA_LEFT
    )) for h in headers]]
    for row in rows:
        cells = []
        for c in row:
            if isinstance(c, Flowable):
                cells.append(c)
            elif c is None:
                cells.append(Paragraph("", cell_style))
            else:
                cells.append(Paragraph(str(c), cell_style))
        table_data.append(cells)

    table = Table(table_data, colWidths=widths, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563eb")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))

    story.append(table)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


def _resolve_image(src, width_mm, height_mm):
    """Return a reportlab Image flowable from a local path string, or None if unloadable."""
    if not src:
        return None
    path = src
    # /static/uploads/... -> static/uploads/...
    if path.startswith("/"):
        path = path.lstrip("/")
    if not os.path.exists(path):
        return None
    try:
        img = Image(path, width=width_mm, height=height_mm)
        img.hAlign = "CENTER"
        return img
    except Exception:
        return None


def _inventory_table(title, items):
    """A4 portrait inventory list styled on the minimal SERPHAWK template
    (the reference design): white background, dark text, gray secondary text,
    thin light-gray dividers, small product thumbnails, colored stock status."""
    from datetime import datetime

    headers = ["Photo", "Code", "Name", "Category", "Stock", "Min", "Unit", "Status", "Description"]
    widths = [14 * mm, 20 * mm, 40 * mm, 22 * mm, 14 * mm, 12 * mm, 13 * mm, 18 * mm, 27 * mm]

    data = []
    total_stock = 0
    low_count = 0
    out_count = 0
    for it in items:
        cur = it.get("current_stock") or 0
        mn = it.get("min_stock") or 0
        try:
            cur = float(cur)
        except (TypeError, ValueError):
            cur = 0
        try:
            mn = float(mn)
        except (TypeError, ValueError):
            mn = 0
        cur_int = int(cur)
        mn_int = int(mn)
        total_stock += cur_int
        if cur_int <= 0:
            status, kind = "Out of Stock", "bad"
            out_count += 1
        elif cur_int <= mn_int:
            status, kind = "Low Stock", "warn"
            low_count += 1
        else:
            status, kind = "In Stock", "ok"

        img = _receipt_image_flowable(it.get("photo_url"), 12 * mm) or _ImagePlaceholder(12 * mm, 12 * mm)
        photo_cell = Table([[img]], colWidths=[14 * mm])
        photo_cell.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]))

        def c_txt(v, fs=8.5, color=_RECEIPT_INK, align=TA_LEFT):
            return Paragraph(str(v), ParagraphStyle(
                "ic", fontName="Helvetica", fontSize=fs, leading=11, textColor=color,
                alignment=align, spaceBefore=0, spaceAfter=0, wordWrap="CJK"))

        data.append([
            photo_cell,
            c_txt(it.get("code") or "—", color=_CATALOG_MUTED),
            c_txt(it.get("name") or "—", fs=9),
            c_txt(it.get("category") or "—", color=_RECEIPT_SUBTLE),
            c_txt(cur_int, align=TA_RIGHT),
            c_txt(mn_int, align=TA_RIGHT, color=_CATALOG_MUTED),
            c_txt(it.get("unit") or "—", color=_RECEIPT_SUBTLE),
            _status_para(status, kind),
            c_txt(it.get("description") or "", fs=7.5, color=_CATALOG_MUTED),
        ])

    summary = [
        ("Total Items", str(len(items))),
        ("Units in Stock", str(total_stock)),
        ("Low Stock", str(low_count)),
        ("Out of Stock", str(out_count)),
    ]
    return _catalog_table_template(title, headers, widths, data, summary=summary, footer_label="SCM BPO · Inventario")


def inventory_pdf(items):
    """Generate a PDF of the inventory list (same structure as selected-item export)."""
    return _inventory_table("Inventory List", items)


def _item_card_story(it, doc):
    """Return a list of flowables rendering one inventory item card."""
    from reportlab.lib import colors as _colors
    from reportlab.lib.styles import getSampleStyleSheet as _gss, ParagraphStyle as _PS
    from reportlab.platypus import Paragraph as _P, Spacer as _Sp, Table as _T, TableStyle as _TS

    styles = _gss()
    story = []
    story.append(_P(f"<b>{it.get('name') or 'Inventory Item'}</b>", _PS(
        "itemTitle", parent=styles["Heading1"], fontSize=20, leading=24,
        textColor=_colors.HexColor("#0f172a"), spaceAfter=2)))
    story.append(_P(f"Code: {it.get('code') or '—'}", _PS(
        "itemCode", parent=styles["BodyText"], fontSize=11, textColor=_colors.HexColor("#64748b"), spaceAfter=8)))

    info = [
        ("Category", it.get("category") or "—"),
        ("Unit", it.get("unit") or "—"),
        ("Current Stock", it.get("current_stock") or 0),
        ("Min Stock", it.get("min_stock") or 0),
    ]
    rows = [[_P(f"<b>{k}</b>", _PS("lk", parent=styles["BodyText"], fontSize=10, textColor=_colors.HexColor("#475569"))),
             _P(str(v), _PS("lv", parent=styles["BodyText"], fontSize=10, textColor=_colors.HexColor("#0f172a")))]
            for k, v in info]
    info_table = _T(rows, colWidths=[40 * mm, 120 * mm])
    info_table.setStyle(_TS([
        ("BACKGROUND", (0, 0), (0, -1), _colors.HexColor("#f1f5f9")),
        ("GRID", (0, 0), (-1, -1), 0.4, _colors.HexColor("#cbd5e1")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(info_table)
    if it.get("description"):
        story.append(_Sp(1, 6))
        from reportlab.lib.styles import ParagraphStyle as _PS2
        story.append(_P(f"<b>Description:</b> {it.get('description')}", _PS2(
            "desc", parent=styles["BodyText"], fontSize=10, textColor=_colors.HexColor("#334155"))))
    return story


def single_inventory_pdf(it, suppliers=None):
    """Generate a single inventory item card PDF."""
    import io as _io
    from reportlab.platypus import SimpleDocTemplate as _SDT

    buf = _io.BytesIO()
    doc = _SDT(buf, pagesize=A4, leftMargin=15 * mm, rightMargin=15 * mm,
               topMargin=15 * mm, bottomMargin=15 * mm)

    story = _brand_header(doc, "Inventory Item")
    story += _item_card_story(it, doc)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


def multi_inventory_pdf(items):
    """Generate a PDF for multiple selected inventory items.

    Uses the exact same landscape table layout as the full inventory list and
    the product catalog, so every export keeps an identical structure.
    """
    return _inventory_table("Inventory Items", items)


def catalog_pdf(products, currency="MXN"):
    """Generate a polished A4 portrait PDF of the product catalog,
    matching the minimal SERPHAWK template used by the inventory export."""
    headers = ["Photo", "SKU", "Name", "Category", "Price", "Tax", "Stock", "Status", "Description"]
    widths = [14 * mm, 20 * mm, 38 * mm, 22 * mm, 18 * mm, 12 * mm, 14 * mm, 17 * mm, 25 * mm]
    currency = str(currency or "MXN")

    data = []
    total_value = 0.0
    for p in products:
        price = p.get("unit_price")
        try:
            price_f = float(price or 0)
        except (TypeError, ValueError):
            price_f = 0.0
        stock = p.get("stock_quantity")
        try:
            stock_f = float(stock or 0)
        except (TypeError, ValueError):
            stock_f = 0
        stock_int = int(stock_f)
        total_value += price_f * stock_f

        active = bool(p.get("is_active"))
        if not active:
            status, kind = "Inactive", "muted"
        elif stock_int <= 0:
            status, kind = "Out of Stock", "bad"
        elif stock_int <= 5:
            status, kind = "Low Stock", "warn"
        else:
            status, kind = "Active", "ok"

        img = _receipt_image_flowable(p.get("photo_url"), 12 * mm) or _ImagePlaceholder(12 * mm, 12 * mm)
        photo_cell = Table([[img]], colWidths=[14 * mm])
        photo_cell.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]))

        def c_txt(v, fs=8.5, color=_RECEIPT_INK, align=TA_LEFT):
            return Paragraph(str(v), ParagraphStyle(
                "cc", fontName="Helvetica", fontSize=fs, leading=11, textColor=color,
                alignment=align, spaceBefore=0, spaceAfter=0, wordWrap="CJK"))

        tax = p.get("tax_rate")
        if tax is None or tax == "" or tax == 0:
            tax_txt = "—"
        else:
            tax_txt = f"{tax}%"

        data.append([
            photo_cell,
            c_txt(p.get("sku") or "—", color=_CATALOG_MUTED),
            c_txt(p.get("name") or "—", fs=9),
            c_txt(p.get("category") or "—", color=_RECEIPT_SUBTLE),
            c_txt(f"{price_f:,.2f} {_currency_symbol(currency)}", align=TA_RIGHT, fs=9),
            c_txt(tax_txt, color=_CATALOG_MUTED, align=TA_RIGHT),
            c_txt(stock_int, align=TA_RIGHT),
            _status_para(status, kind),
            c_txt(p.get("description") or "", fs=7.5, color=_CATALOG_MUTED),
        ])

    summary = [
        ("Products", str(len(products))),
        ("Items in Stock", str(int(sum(float(p.get("stock_quantity") or 0) for p in products)))),
        ("Catalog Value", f"{total_value:,.2f} {_currency_symbol(currency)}"),
    ]
    meta = [("Export:", "Product Catalog"), ("Currency:", str(currency).upper())]
    return _catalog_table_template("Product Catalog", headers, widths, data,
                                   meta_left=meta, summary=summary,
                                   footer_label="SCM BPO · Catálogo de Productos")


def send_pdf_email(to_email, subject, body, pdf_bytes, filename):
    """Send a PDF attachment via the configured SMTP. Best-effort.
    The body is automatically wrapped in the branded SerpHawk email template
    with the logo in the header and the attachment clearly called out."""
    from modules.email_sender import send_email_outlook, branded_email, _attachment_note
    sender = os.environ.get("EMAIL_SENDER") or os.environ.get("OUTLOOK_EMAIL") or ""
    password = os.environ.get("EMAIL_PASSWORD") or os.environ.get("OUTLOOK_PASSWORD") or ""
    if not sender or not password:
        raise RuntimeError("SMTP not configured (missing EMAIL_SENDER/EMAIL_PASSWORD)")
    smtp_server = os.environ.get("SMTP_SERVER") or os.environ.get("EMAIL_HOST") or "mail.serphawk.in"
    smtp_port = int(os.environ.get("SMTP_PORT") or os.environ.get("EMAIL_PORT") or 587)
    content = body if isinstance(body, str) and body.lstrip().startswith("<") else f"<p>{body}</p>"
    full_body = branded_email(title=subject, body_html=content + _attachment_note(filename))
    send_email_outlook(
        to_email=to_email,
        subject=subject,
        body=full_body,
        sender_email=sender,
        sender_password=password,
        smtp_server=smtp_server,
        smtp_port=smtp_port,
        attachments=[(filename, pdf_bytes, "application/pdf")],
    )


# ── Sales Order PDF helpers ──────────────────────────────────────────────

def sales_order_pdf(orders):
    """Generate a PDF table of all sales orders."""
    title = "Sales Orders"
    headers = ["Order #", "Client", "Amount", "Currency", "Status", "Delivery Date", "Created"]
    widths = [30 * mm, 40 * mm, 28 * mm, 20 * mm, 24 * mm, 30 * mm, 30 * mm]

    rows = []
    for o in orders:
        created = ""
        if o.get("created_at"):
            try:
                created = o["created_at"][:10]
            except Exception:
                created = str(o["created_at"])[:10]
        rows.append([
            o.get("order_number") or "—",
            o.get("client_name") or "—",
            f"{o.get('grand_total', 0):,.2f}",
            o.get("currency") or "USD",
            o.get("status") or "—",
            o.get("delivery_date") or "—",
            created,
        ])
    return _build_pdf(title, headers, rows, widths)


def _single_order_card_story(label, fields, doc):
    """Return flowables for a single order card (reused by sales & purchase)."""
    from reportlab.lib.styles import getSampleStyleSheet as _gss, ParagraphStyle as _PS
    from reportlab.platypus import Paragraph as _P, Spacer as _Sp, Table as _T, TableStyle as _TS

    styles = _gss()
    story = []

    title_style = _PS("orderTitle", parent=styles["Heading1"], fontSize=20, leading=24,
                       textColor=colors.HexColor("#0f172a"), spaceAfter=2)
    story.append(_P(f"<b>{label}</b>", title_style))

    rows = []
    for k, v in fields:
        key_p = _P(f"<b>{k}</b>", _PS("fk", parent=styles["BodyText"], fontSize=10,
                                       textColor=colors.HexColor("#475569")))
        val_p = _P(str(v) if v is not None else "—", _PS("fv", parent=styles["BodyText"],
                                                          fontSize=10, textColor=colors.HexColor("#0f172a")))
        rows.append([key_p, val_p])

    info_table = _T(rows, colWidths=[45 * mm, 120 * mm])
    info_table.setStyle(_TS([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(_Sp(1, 4 * mm))
    story.append(info_table)
    return story


def single_sales_order_pdf(order, client_name=None, lead_name=None, party=None):
    """Generate a branded, good-looking single Sales Order PDF (A4 portrait).

    ``order`` is a dict (e.g. ``SalesOrder.model_dump()``). ``party`` is an
    optional dict with keys: name, company, email, phone, address.
    """
    from datetime import datetime as _dt

    party = party or {}
    currency = str(order.get("currency") or "USD")
    qty_total = float(order.get("grand_total") or 0)
    qn = order.get("order_number") or str(order.get("id") or "")

    created = order.get("created_at") or ""
    try:
        if hasattr(created, "strftime"):
            created = created.strftime("%b %d, %Y")
        else:
            created = _dt.fromisoformat(str(created).replace("Z", "+00:00")).strftime("%b %d, %Y")
    except Exception:
        created = str(created)[:10] or ""

    delivery = order.get("delivery_date") or "—"
    if hasattr(delivery, "strftime"):
        delivery = delivery.strftime("%b %d, %Y")

    status = (order.get("status") or "—").strip()
    if not status:
        status = "—"
    status_color = {
        "Draft": colors.HexColor("#64748b"),
        "Pending": colors.HexColor("#d97706"),
        "Sent": colors.HexColor("#059669"),
        "Received": colors.HexColor("#2563eb"),
        "Canceled": colors.HexColor("#dc2626"),
        "Cancelled": colors.HexColor("#dc2626"),
    }.get(status, colors.HexColor("#64748b"))

    def P(text, style):
        return Paragraph(str(text or "") if text is not None else "", style)

    def cell(fs=9, ls=12, color=_RECEIPT_INK, align=TA_LEFT, bold=False, wrap=True):
        return ParagraphStyle(
            "soP", fontName="Helvetica-Bold" if bold else "Helvetica",
            fontSize=fs, leading=ls, textColor=color, alignment=align,
            spaceBefore=0, spaceAfter=0, wordWrap="CJK" if wrap else None,
        )

    def zero_pad_style():
        return TableStyle([
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ])

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=15 * mm, rightMargin=15 * mm,
        topMargin=16 * mm, bottomMargin=20 * mm,
        title=f"SCM BPO — Sales Order {qn}", author="SCM BPO",
    )
    story = []

    # ── 1) Header ────────────────────────────────────────────────────────
    logo_flowable = _receipt_image_flowable("static/logo.png", 35 * mm)
    if logo_flowable:
        left_parts = [
            logo_flowable,
            Spacer(1, 2 * mm),
            Paragraph("Sales Order", ParagraphStyle(
                "soSub", fontName="Helvetica", fontSize=9.5, leading=12,
                textColor=_RECEIPT_SUBTLE, wordWrap="CJK", spaceBefore=3)),
        ]
    else:
        left_parts = [
            Paragraph("SCM BPO", ParagraphStyle(
                "soBrand", fontName="Helvetica-Bold", fontSize=17, leading=20,
                textColor=_RECEIPT_INK, wordWrap="CJK")),
            Paragraph("Sales Order", ParagraphStyle(
                "soSub", fontName="Helvetica", fontSize=9.5, leading=12,
                textColor=_RECEIPT_SUBTLE, wordWrap="CJK", spaceBefore=3)),
        ]
    left_cell = Table([[p] for p in left_parts], colWidths=[None])
    left_cell.setStyle(zero_pad_style())

    meta = []
    if qn:
        meta.append(P(f"<b>Order:</b>&nbsp;&nbsp;{qn}", ParagraphStyle(
            "soMeta0", fontSize=11, leading=14, textColor=_RECEIPT_INK,
            alignment=TA_RIGHT, wordWrap="CJK")))
    if created:
        meta.append(P(f"<b>Date:</b>&nbsp;&nbsp;{created}", ParagraphStyle(
            "soMeta1", fontSize=8.5, leading=12, textColor=_RECEIPT_FAINT,
            alignment=TA_RIGHT, wordWrap="CJK")))
    if meta:
        right_cell = Table([[p] for p in meta], colWidths=[None])
        meta_style = [
            ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]
        for mi in range(len(meta)):
            meta_style.append(("TOPPADDING", (0, mi), (0, mi), 6 if mi else 2))
        right_cell.setStyle(TableStyle(meta_style))
        header_table = Table([[left_cell, right_cell]], colWidths=[100 * mm, 80 * mm])
    else:
        header_table = Table([[left_cell]], colWidths=[180 * mm])
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 5 * mm))
    story.append(HRFlowable(width="100%", thickness=0.6, color=_RECEIPT_LINE, spaceBefore=0, spaceAfter=0))
    story.append(Spacer(1, 6 * mm))

    handle = party.get("name") or order.get("recipient_name") or client_name or lead_name or "—"
    bill_lines = [P(handle, cell(11, 14, _RECEIPT_INK, bold=True, wrap=True))]
    for label, value in [("Company", party.get("company")), ("Email", party.get("email")),
                         ("Phone", party.get("phone")), ("Address", party.get("address"))]:
        if value:
            bill_lines.append(P(f"<b>{label}:</b> {value}", cell(8.5, 12, _RECEIPT_SUBTLE)))

    from_lines = [
        P("SCM SHIPPING SERVICES PVT LTD", cell(11, 14, _RECEIPT_INK, bold=True, wrap=True)),
        P("Koyenco Techpark, Kepip, Infopark P.O.,", cell(8.5, 12, _RECEIPT_SUBTLE)),
        P("Kakkanad, Cochin", cell(8.5, 12, _RECEIPT_SUBTLE)),
        P("<b>Phone:</b> +91-9947950099", cell(8.5, 12, _RECEIPT_SUBTLE)),
        P("<b>Email:</b> contact@scmbpo.com", cell(8.5, 12, _RECEIPT_SUBTLE)),
        P("<b>Web:</b> www.scmbpo.com", cell(8.5, 12, _RECEIPT_SUBTLE)),
    ]

    bill_heading = Table([[P("ORDER FOR", cell(7.5, 9, _RECEIPT_FAINT, bold=True))]], colWidths=[80 * mm])
    from_heading = Table([[P("FROM", cell(7.5, 9, _RECEIPT_FAINT, bold=True))]], colWidths=[80 * mm])
    
    pad_style = TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ])
    bill_heading.setStyle(pad_style)
    from_heading.setStyle(pad_style)

    info_cell = Table([[p] for p in bill_lines], colWidths=[None])
    info_cell.setStyle(zero_pad_style())
    from_cell = Table([[p] for p in from_lines], colWidths=[None])
    from_cell.setStyle(zero_pad_style())

    story.append(Table([[from_heading, bill_heading], [from_cell, info_cell]], colWidths=[90 * mm, 90 * mm], style=TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ])))
    story.append(Spacer(1, 8 * mm))

    # ── 3) Details grid ──────────────────────────────────────────────────
    def info_box(label, value, value_color=_RECEIPT_INK):
        inner = Table([
            [P(label.upper(), cell(6.5, 8, _RECEIPT_FAINT, bold=True))],
            [P(str(value), cell(10, 13, value_color, bold=True, wrap=True))],
        ], colWidths=[None])
        inner.setStyle(TableStyle([
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (0, 0), 0),
            ("TOPPADDING", (0, 1), (0, 1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]))
        box = Table([[inner]], colWidths=[None])
        box.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
            ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#e2e8f0")),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ]))
        return box

    grid = Table([
        [info_box("Amount", f"{currency} {qty_total:,.2f}"),
         info_box("Delivery Date", delivery),
         info_box("Status", status, value_color=status_color)],
        [info_box("Order #", qn or "—"),
         info_box("Created", created or "—"),
         info_box("Currency", currency)],
    ], colWidths=[60 * mm, 60 * mm, 60 * mm])
    grid.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(grid)

    notes = order.get("notes")
    if notes:
        story.append(Spacer(1, 5 * mm))
        story.append(info_box("Notes", notes))

    # ── 4) Grand total panel ─────────────────────────────────────────────
    total_inner = Table([
        [P("GRAND TOTAL", cell(8, 10, colors.HexColor("#b9c6f9"), bold=True))],
        [P(f"{currency} {qty_total:,.2f}", cell(17, 22, colors.white, bold=True, wrap=True))],
    ], colWidths=[None])
    total_inner.setStyle(TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (0, 0), 0),
        ("TOPPADDING", (0, 1), (0, 1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    total_panel = Table([[total_inner]], colWidths=[None])
    total_panel.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#1d4ed8")),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
    ]))
    story.append(Spacer(1, 8 * mm))
    story.append(Table([[Spacer(1, 1), total_panel]], colWidths=[110 * mm, 70 * mm], style=TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ])))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


# ── Purchase Order PDF helpers ───────────────────────────────────────────

def purchase_order_pdf(orders):
    """Generate a PDF table of all purchase orders."""
    title = "Purchase Orders"
    headers = ["PO #", "Vendor", "Email", "Amount", "Currency", "Status", "Expected Delivery", "Created"]
    widths = [25 * mm, 32 * mm, 40 * mm, 24 * mm, 18 * mm, 22 * mm, 30 * mm, 28 * mm]

    rows = []
    for o in orders:
        created = ""
        if o.get("created_at"):
            try:
                created = o["created_at"][:10]
            except Exception:
                created = str(o["created_at"])[:10]
        rows.append([
            o.get("po_number") or "—",
            o.get("vendor_name") or "—",
            o.get("vendor_email") or "—",
            f"{o.get('grand_total', 0):,.2f}",
            o.get("currency") or "USD",
            o.get("status") or "—",
            o.get("expected_delivery") or "—",
            created,
        ])
    return _build_pdf(title, headers, rows, widths)


def single_purchase_order_pdf(order):
    """Generate a single purchase order PDF card."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=15 * mm, rightMargin=15 * mm,
                            topMargin=15 * mm, bottomMargin=15 * mm)

    created = ""
    if order.get("created_at"):
        try:
            created = order["created_at"][:10]
        except Exception:
            created = str(order["created_at"])[:10]

    fields = [
        ("PO Number", order.get("po_number") or "—"),
        ("Status", order.get("status") or "—"),
        ("Vendor Name", order.get("vendor_name") or "—"),
        ("Vendor Email", order.get("vendor_email") or "—"),
        ("Grand Total", f"{order.get('currency', 'USD')} {order.get('grand_total', 0):,.2f}"),
        ("Expected Delivery", order.get("expected_delivery") or "—"),
        ("Notes", order.get("notes") or "—"),
        ("Created", created),
    ]
    story = _brand_header(doc, "Purchase Order")
    story += _single_order_card_story(f"Purchase Order — {order.get('po_number') or order.get('id', '')}", fields, doc)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


# ── POS Receipt / Invoice PDF (A4 portrait) ───────────────────────────────

_RECEIPT_INK = colors.HexColor("#0f172a")      # near-black body text
_RECEIPT_SUBTLE = colors.HexColor("#64748b")   # muted labels
_RECEIPT_FAINT = colors.HexColor("#94a3b8")    # faint detail text
_RECEIPT_LINE = colors.HexColor("#e2e8f0")     # thin light-gray dividers

_CURRENCY_SYMBOLS = {
    "USD": "$", "MXN": "$", "COP": "$", "BRL": "R$", "EUR": "€",
    "GBP": "£", "INR": "₹", "PEN": "S/", "ARS": "$", "CLP": "$",
}


def _currency_symbol(currency):
    """Map a currency code to its symbol; anything else is used literally."""
    if not currency:
        return "$"
    symbol = _CURRENCY_SYMBOLS.get(str(currency).upper())
    return symbol if symbol is not None else str(currency)


def _receipt_money(value, currency):
    """Format a monetary value, e.g. 149.94 -> '$149.94'."""
    try:
        return f"{_currency_symbol(currency)}{float(value):,.2f}"
    except (TypeError, ValueError):
        return f"{_currency_symbol(currency)}0.00"


class _ImagePlaceholder(Flowable):
    """Small light-gray placeholder shown when a product has no usable image."""

    def __init__(self, width, height):
        super().__init__()
        self.width = width
        self.height = height

    def draw(self):
        c = self.canv
        c.saveState()
        c.setFillColor(colors.HexColor("#f1f5f9"))
        c.roundRect(0, 0, self.width, self.height, self.width * 0.12, fill=1, stroke=0)
        c.setFillColor(colors.HexColor("#cbd5e1"))
        # simple "photo" glyph: sky + mountain + sun
        c.circle(self.width * 0.76, self.height * 0.66, self.width * 0.09, fill=1, stroke=0)
        c.rect(self.width * 0.22, self.height * 0.18, self.width * 0.56, self.height * 0.30, fill=1, stroke=0)
        p = c.beginPath()
        p.moveTo(self.width * 0.22, self.height * 0.48)
        p.lineTo(self.width * 0.40, self.height * 0.70)
        p.lineTo(self.width * 0.52, self.height * 0.56)
        p.lineTo(self.width * 0.62, self.height * 0.64)
        p.lineTo(self.width * 0.78, self.height * 0.48)
        p.lineTo(self.width * 0.78, self.height * 0.22)
        p.close()
        c.drawPath(p, fill=1, stroke=0)
        c.restoreState()


def _receipt_image_flowable(src, box=12 * mm):
    """Fit a product image inside a square box without distortion."""
    if not src:
        return None
    path = str(src).lstrip("/")
    if not os.path.exists(path):
        return None
    try:
        from reportlab.lib.utils import ImageReader
        reader = ImageReader(path)
        iw, ih = reader.getSize()
        if iw <= 0 or ih <= 0:
            return None
        scale = min(box / float(iw), box / float(ih))
        img = Image(path, width=float(iw) * scale, height=float(ih) * scale)
        img.hAlign = "LEFT"
        return img
    except Exception:
        return None


_CATALOG_OK = colors.HexColor("#059669")     # in stock / active
_CATALOG_WARN = colors.HexColor("#d97706")   # low stock
_CATALOG_BAD = colors.HexColor("#dc2626")    # out of stock / inactive
_CATALOG_MUTED = colors.HexColor("#94a3b8")  # neutral status


def _status_para(text, kind, font_size=8.5, ls=11):
    """Return a colored status Paragraph (no filled pill, minimal template)."""
    color = {
        "ok": _CATALOG_OK, "warn": _CATALOG_WARN, "bad": _CATALOG_BAD, "muted": _CATALOG_MUTED,
    }.get(kind, _CATALOG_MUTED)
    return Paragraph(str(text), ParagraphStyle(
        "st", fontName="Helvetica-Bold", fontSize=font_size, leading=ls,
        textColor=color, alignment=TA_LEFT, spaceBefore=0, spaceAfter=0, wordWrap="CJK"))


def _catalog_table_template(title, headers, widths, data, meta_left=None, summary=None, footer_label=None):
    """Render a polished A4-portrait SERPHAWK table document.

    Shared by inventory list and product catalog so both exports look identical:
    minimal brand header, gray text labels, thin dividers, zebra-free rows,
    colored statuses and a compact page footer.
    """
    from datetime import datetime

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=15 * mm, rightMargin=15 * mm,
        topMargin=14 * mm, bottomMargin=16 * mm,
        title=title, author="SCM BPO",
    )

    def cell(fs=9, ls=12, color=_RECEIPT_INK, align=TA_LEFT, bold=False, wrap=True):
        return ParagraphStyle(
            "cc", fontName="Helvetica-Bold" if bold else "Helvetica",
            fontSize=fs, leading=ls, textColor=color, alignment=align,
            spaceBefore=0, spaceAfter=0, wordWrap="CJK" if wrap else None,
        )

    meta_lines = [("Date:", _english_datetime(datetime.now())), ("Records:", str(len(data)))]
    if meta_left:
        meta_lines = meta_left + meta_lines

    story = []
    story += _serphawk_header(
        "SCM BPO", meta_lines, subtitle=title,
    )

    table_data = [[Paragraph(h, cell(7.5, 10, _CATALOG_MUTED, align=TA_LEFT, bold=True)) for h in headers]]
    for row in data:
        table_data.append([
            c if isinstance(c, Flowable) else (Paragraph(str(c), cell(8.5, 11, _RECEIPT_INK, align=TA_LEFT)) if not isinstance(c, Paragraph) else c)
            for c in row
        ])

    style = [
        ("VALIGN", (0, 0), (-1, 0), "BOTTOM"),
        ("VALIGN", (0, 1), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 3),
        ("RIGHTPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING", (0, 0), (-1, 0), 0),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 4),
        ("TOPPADDING", (0, 1), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
        ("LINEBELOW", (0, 0), (-1, 0), 0.6, _RECEIPT_LINE),
    ]
    for idx in range(1, len(table_data)):
        style.append(("LINEBELOW", (0, idx), (-1, idx), 0.4, colors.HexColor("#eef2f7")))

    table = Table(table_data, colWidths=widths, repeatRows=1)
    table.setStyle(TableStyle(style))
    story.append(table)

    # Summary band (e.g. total items / total value)
    if summary:
        story.append(Spacer(1, 5 * mm))
        summary_rows = [[
            Paragraph(k, cell(8, 10, _CATALOG_MUTED, align=TA_RIGHT, bold=True)),
            Paragraph(v, cell(9, 12, _RECEIPT_INK, align=TA_RIGHT, bold=True)),
        ] for k, v in summary]
        st = Table(summary_rows, colWidths=[120 * mm, 60 * mm])
        st.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LINEABOVE", (0, 0), (-1, -1), 0.6, _RECEIPT_LINE),
        ]))
        story.append(KeepTogether([st]))

    def _inventory_footer(canvas, _doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(_CATALOG_MUTED)
        canvas.drawString(15 * mm, 9 * mm, (footer_label or title))
        canvas.drawRightString(A4[0] - 15 * mm, 9 * mm, f"Página {_doc.page}")
        canvas.restoreState()

    doc.build(story, onFirstPage=_inventory_footer, onLaterPages=_inventory_footer)
    return buf.getvalue()


_MESES_ES = [
    "enero", "febrero", "marzo", "abril", "mayo", "junio",
    "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre",
]


def _spanish_datetime(dt):
    """Format a datetime like the reference receipt, e.g.
    '6 de julio de 2026 a las 11:02:23 p.m.'"""
    if dt is None:
        return ""
    return (
        f"{dt.day} de {_MESES_ES[dt.month - 1]} de {dt.year} "
        f"a las {dt.strftime('%I:%M:%S')} {dt.strftime('%p').lower()}"
    )


def _english_datetime(dt):
    """Format a datetime in English, e.g. 'Sep 10, 2026 at 4:38 PM'."""
    if dt is None:
        return ""
    return dt.strftime("%b %d, %Y at %I:%M %p").replace(" 0", " ")


def _serphawk_header(title_text, meta_lines=None, subtitle=None):
    """Shared minimal SERPHAWK document header (reference-template).

    Bold brand at the top-left, small metadata block at the top-right, then a
    thin light-gray divider. Every document built on this template (receipt,
    inventory list, ...) shares the exact same typography / spacing / margins.

    ``meta_lines`` is a list of ``(label, value)`` tuples rendered right-aligned
    with bold labels and normal-weight values, e.g. ("Ticket:", "#2").
    """
    from reportlab.platypus import HRFlowable as _HR

    logo_flowable = _receipt_image_flowable("static/logo.png", 35 * mm)
    if logo_flowable:
        left_parts = [logo_flowable, Spacer(1, 2 * mm)]
    else:
        left_parts = [Paragraph(title_text, ParagraphStyle(
            "shBrand", fontName="Helvetica-Bold", fontSize=16, leading=19,
            textColor=_RECEIPT_INK, wordWrap="CJK"))]

    if subtitle:
        left_parts.append(Paragraph(subtitle, ParagraphStyle(
            "shSub", fontName="Helvetica", fontSize=9.5, leading=12,
            textColor=_RECEIPT_SUBTLE, wordWrap="CJK", spaceBefore=2)))

    right_cell = None
    if meta_lines:
        meta_paras = [
            Paragraph(f"<b>{label}</b> {value}", ParagraphStyle(
                "shMeta", fontName="Helvetica", fontSize=9, leading=12,
                textColor=_RECEIPT_INK, alignment=TA_RIGHT, wordWrap="CJK"))
            for label, value in meta_lines
        ]
        right_cell = Table([[p] for p in meta_paras], colWidths=[None])
        right_cell.setStyle(TableStyle([
            ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 1.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]))

    left_cell = Table([[p] for p in left_parts], colWidths=[None])
    left_cell.setStyle(TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))

    if right_cell is not None:
        header_table = Table([[left_cell, right_cell]], colWidths=[100 * mm, 80 * mm])
    else:
        header_table = Table([[left_cell]], colWidths=[180 * mm])
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    flow = [header_table, Spacer(1, 5 * mm)]
    flow.append(_HR(width="100%", thickness=0.6, color=_RECEIPT_LINE, spaceBefore=0, spaceAfter=0))
    flow.append(Spacer(1, 5 * mm))
    return flow


def pos_receipt_pdf(data):
    """Generate a clean, minimal A4 portrait POS receipt / invoice in Spanish.

    Accepted payload (all keys optional, calculations are automatic):

        companyName  : store name, defaults to "SERPHAWK"
        ticketNumber : e.g. 2  -> displayed as "Ticket: #2"
        date         : display string, e.g. "6 de julio de 2026 a las 11:02:23 p.m."
        customer     : defaults to "Público en General"
        products     : [ { name, image, quantity, unitPrice, subtotal } ]
        subtotal     : overall subtotal (falls back to sum of line items)
        taxRate      : e.g. 16 (percent). Default 0.
        taxAmount    : explicit tax amount (computed if omitted)
        total        : explicit total (computed if omitted)
        paymentMethod: e.g. "Efectivo"
        amountPaid   : money handed over (defaults to total)
        change       : change due (computed as amountPaid - total)
        currency     : currency code or literal symbol, defaults to "$"
        taxLabel     : label prefix, defaults to "IVA"
        taxIncluded  : True  -> tax is inside the total (Total == Subtotal),
                       False -> tax is added on top (Total = Subtotal + tax)

    Returns raw PDF bytes.
    """
    company_name = str(data.get("companyName") or "SERPHAWK")
    ticket = data.get("ticketNumber")
    ticket_str = f"#{ticket}" if ticket is not None and str(ticket) != "" else ""
    date_str = str(data.get("date") or "")
    customer = str(data.get("customer") or "Público en General")
    currency = data.get("currency") or "$"
    tax_rate = data.get("taxRate") or 0
    try:
        tax_rate = float(tax_rate)
    except (TypeError, ValueError):
        tax_rate = 0
    tax_included = bool(data.get("taxIncluded", True))
    tax_label = str(data.get("taxLabel") or "IVA")

    # 1/3 line totals + money
    products = data.get("products") or []
    line_rows = []
    subtotal = 0.0
    for p in products:
        qty = float(p.get("quantity") or 0)
        unit = float(p.get("unitPrice") or 0)
        line_total = round(qty * unit, 2)
        if p.get("subtotal") is not None:
            try:
                line_total = round(float(p["subtotal"]), 2)
            except (TypeError, ValueError):
                pass
        subtotal += line_total
        line_rows.append({
            "name": str(p.get("name") or "Producto"),
            "image": p.get("image"),
            "quantity": qty,
            "unit_price": unit,
            "subtotal": line_total,
        })
    subtotal = round(subtotal, 2)

    tax_amount = data.get("taxAmount")
    if tax_amount is None:
        if tax_included and tax_rate > 0:
            tax_amount = round(subtotal - subtotal / (1 + tax_rate / 100.0), 2)
        else:
            tax_amount = round(subtotal * tax_rate / 100.0, 2)
    tax_amount = round(float(tax_amount or 0), 2)

    total = data.get("total")
    if total is None:
        total = subtotal if tax_included else round(subtotal + tax_amount, 2)
    total = round(float(total or 0), 2)

    amount_paid = data.get("amountPaid")
    if amount_paid is None:
        amount_paid = total
    amount_paid = round(float(amount_paid or 0), 2)
    change = round(amount_paid - total, 2)
    payment = str(data.get("paymentMethod") or "Efectivo")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=15 * mm, rightMargin=15 * mm,
        topMargin=14 * mm, bottomMargin=16 * mm,
        title=f"{company_name} — Ticket {ticket_str}",
        author=company_name,
    )

    def base(font_size=9, leading=12, color=_RECEIPT_INK, align=TA_LEFT, bold=False, wrap=True):
        return ParagraphStyle(
            "r", fontName="Helvetica-Bold" if bold else "Helvetica",
            fontSize=font_size, leading=leading, textColor=color,
            alignment=align, spaceBefore=0, spaceAfter=0, wordWrap="CJK" if wrap else None,
        )

    # ── Header ───────────────────────────────────────────────────────────
    meta_lines = []
    if ticket_str:
        meta_lines.append(("Ticket:", ticket_str))
    if date_str:
        meta_lines.append(("Fecha:", date_str))
    meta_lines.append(("Cliente:", customer))
    story = _serphawk_header(company_name, meta_lines if meta_lines else None)

    # ── Product table ────────────────────────────────────────────────────
    w_product, w_qty, w_price, w_sub = 90 * mm, 27 * mm, 36 * mm, 27 * mm

    def header_cell(text):
        return Paragraph(text, base(7.5, 10, _RECEIPT_SUBTLE, TA_LEFT, bold=True))

    table_data = [[
        header_cell("Producto"),
        header_cell("Cantidad"),
        header_cell("Precio Unitario"),
        header_cell("Subtotal"),
    ]]

    name_col = ParagraphStyle("rname", parent=base(9, 12, _RECEIPT_INK), wordWrap="CJK")

    for idx, row in enumerate(line_rows):
        img = _receipt_image_flowable(row["image"], 12 * mm) or _ImagePlaceholder(12 * mm, 12 * mm)
        name_para = Paragraph(row["name"], name_col)
        name_cell = Table([[img, name_para]], colWidths=[12 * mm, w_product - 12 * mm - 4])
        name_cell.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ALIGN", (0, 0), (0, 0), "LEFT"),
            ("ALIGN", (1, 0), (1, 0), "LEFT"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]))

        qty = row["quantity"]
        qty_text = f"{qty:g} {'unidad' if qty == 1 else 'unidades'}"
        table_data.append([
            name_cell,
            Paragraph(qty_text, base(9, 12, _RECEIPT_INK, TA_LEFT)),
            Paragraph(_receipt_money(row["unit_price"], currency), base(9, 12, _RECEIPT_INK, TA_RIGHT)),
            Paragraph(_receipt_money(row["subtotal"], currency), base(9, 12, _RECEIPT_INK, TA_RIGHT)),
        ])

    item_style = [
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (-1, 0), "LEFT"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]
    if line_rows:
        # light dividers between the table sections (header skim line + each row)
        item_style.append(("LINEBELOW", (0, 0), (-1, 0), 0.6, _RECEIPT_LINE))
        for idx in range(1, len(table_data)):
            item_style.append(("LINEBELOW", (0, idx), (-1, idx), 0.5, _RECEIPT_LINE))
        item_style.append(("BOTTOMPADDING", (0, 1), (-1, -1), 5))
        item_style.append(("TOPPADDING", (0, 1), (-1, -1), 5))

    items_table = Table(table_data, colWidths=[w_product, w_qty, w_price, w_sub], repeatRows=1)
    items_table.setStyle(TableStyle(item_style))
    story.append(items_table)
    story.append(Spacer(1, 8 * mm))

    # ── Totals + payment block (kept together, right-aligned) ────────────
    money_right = base(9, 12, _RECEIPT_INK, TA_RIGHT)
    label_right = base(9, 12, _RECEIPT_INK, TA_RIGHT)

    totals = [
        [Paragraph("Subtotal", label_right), Paragraph(_receipt_money(subtotal, currency), money_right)],
    ]
    totals.append([
        Paragraph("Total", base(10, 13, _RECEIPT_INK, TA_RIGHT, bold=True)),
        Paragraph(_receipt_money(total, currency), base(10, 13, _RECEIPT_INK, TA_RIGHT, bold=True)),
    ])
    if tax_rate > 0:
        totals.append([
            Paragraph(f"{tax_label} {tax_rate:g}% Incluido", base(8, 11, _RECEIPT_FAINT, TA_RIGHT)),
            Paragraph(_receipt_money(tax_amount, currency), base(8, 11, _RECEIPT_FAINT, TA_RIGHT)),
        ])
    totals.append([
        Paragraph("Pago", base(8.5, 11, _RECEIPT_SUBTLE, TA_RIGHT, bold=True)),
        Paragraph("", base(8.5, 11)),
    ])
    totals.append([
        Paragraph(payment, label_right),
        Paragraph(_receipt_money(amount_paid, currency), money_right),
    ])
    totals.append([
        Paragraph("Cambio", label_right),
        Paragraph(_receipt_money(change, currency), money_right),
    ])

    totals_table = Table(totals, colWidths=[64 * mm, 56 * mm], hAlign="RIGHT")
    totals_style = [
        ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("LINEABOVE", (0, 1), (-1, 1), 0.6, _RECEIPT_LINE),
        ("LINEBELOW", (0, 1), (-1, 1), 0.6, _RECEIPT_LINE),
        ("TOPPADDING", (0, 1), (-1, 1), 5),
        ("BOTTOMPADDING", (0, 1), (-1, 1), 5),
    ]
    if tax_rate > 0:
        totals_style.append(("LINEABOVE", (0, 2), (-1, 2), 0.6, _RECEIPT_LINE))
        totals_style.append(("LINEBELOW", (0, 2), (-1, 2), 0.6, _RECEIPT_LINE))
        totals_style.append(("TOPPADDING", (0, 2), (-1, 2), 4))
        totals_style.append(("BOTTOMPADDING", (0, 2), (-1, 2), 4))
    totals_table.setStyle(TableStyle(totals_style))

    story.append(KeepTogether([totals_table]))

    # ── Footer (only appears when the receipt spans multiple pages) ──────
    def _receipt_footer(canvas, _doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(_RECEIPT_FAINT)
        canvas.drawRightString(A4[0] - 15 * mm, 9 * mm, f"Ticket {ticket_str} · Página {_doc.page}")
        canvas.restoreState()

    doc.build(story, onFirstPage=lambda c, d: None, onLaterPages=_receipt_footer)
    return buf.getvalue()


def _q_section_title(text):
    return Paragraph(text, ParagraphStyle(
        "qsec", fontName="Helvetica-Bold", fontSize=9, leading=12,
        textColor=_RECEIPT_INK, spaceBefore=0, spaceAfter=0))


class _QuoteCanvas:
    """Canvas subclass that adds 'Page X of Y' footer.

    First layout pass fills ``_saved_page_states`` without finalizing pages.
    On ``save()``, each page state is replayed with the footer drawn before
    the page is flushed to the PDF.
    """
    def __init__(self, *args, **kwargs):
        from reportlab.pdfgen.canvas import Canvas
        self._canvas = Canvas(*args, **kwargs)
        self._saved_page_states = []

    def __getattr__(self, name):
        return getattr(self._canvas, name)

    def __setattr__(self, name, value):
        if name.startswith("_"):
            self.__dict__[name] = value
        else:
            setattr(self._canvas, name, value)

    def showPage(self):
        self._saved_page_states.append(dict(self._canvas.__dict__))
        self._canvas._startPage()

    def save(self):
        total = len(self._saved_page_states)
        for i, state in enumerate(self._saved_page_states, 1):
            self._canvas.__dict__.update(state)
            self._draw_footer(i, total)
            self._canvas.showPage()
        self._canvas.save()

    def _draw_footer(self, page_num, total_pages):
        c = self._canvas
        c.saveState()
        c.setStrokeColor(colors.HexColor("#cbd5e1"))
        c.setLineWidth(0.5)
        c.line(14 * mm, 12 * mm, A4[0] - 14 * mm, 12 * mm)
        c.setFont("Helvetica", 7)
        c.setFillColor(colors.HexColor("#64748b"))
        c.drawString(14 * mm, 8 * mm, "SCM BPO (Division of SCM SHIPPING SERVICES PVT LTD) · Koyenco Techpark, Infopark, Kakkanad, Cochin - 682042")
        c.drawString(14 * mm, 5 * mm, "Confidential Commercial Quotation · contact@scmbpo.com · www.scmbpo.com")
        page_str = f"Page {page_num} of {total_pages}"
        c.drawRightString(A4[0] - 14 * mm, 8 * mm, page_str)
        c.restoreState()


def _number_to_words(n):
    units = ["", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten",
             "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen"]
    tens = ["", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"]
    
    def _helper(num):
        if num == 0:
            return ""
        elif num < 20:
            return units[num] + " "
        elif num < 100:
            return tens[num // 10] + ("-" + units[num % 10] if num % 10 != 0 else "") + " "
        elif num < 1000:
            return units[num // 100] + " Hundred " + _helper(num % 100)
        elif num < 1000000:
            return _helper(num // 1000) + " Thousand " + _helper(num % 1000)
        elif num < 1000000000:
            return _helper(num // 1000000) + " Million " + _helper(num % 1000000)
        else:
            return _helper(num // 1000000000) + " Billion " + _helper(num % 1000000000)

    try:
        val = int(round(float(n)))
        if val <= 0:
            return "Zero"
        return " ".join(_helper(val).split())
    except Exception:
        return ""


def _format_pdf_date(dt):
    if not dt:
        return ""
    if hasattr(dt, "strftime"):
        return dt.strftime("%B %d, %Y")
    s = str(dt)
    try:
        from datetime import datetime as _dt
        parsed = _dt.fromisoformat(s.replace("Z", "+00:00"))
        return parsed.strftime("%B %d, %Y")
    except Exception:
        return s[:10]


def quote_pdf(data):
    """Generate an executive-grade commercial proposal / quotation PDF for SCM BPO (A4 portrait)."""
    from datetime import datetime as _dt, timedelta as _td

    company_name = "SCM BPO"
    legal_name = "SCM SHIPPING SERVICES PVT LTD"
    address_line = "Koyenco Techpark, Kepip, Infopark P.O., Kakkanad, Cochin - 682042"
    contact_phone = "+91-9947950099"
    contact_email = "contact@scmbpo.com"
    website = "www.scmbpo.com"

    currency = str(data.get("currency") or "MXN").upper()
    curr_sym = "₹" if currency == "INR" else ("$" if currency in ("USD", "MXN", "CAD", "AUD") else f"{currency} ")
    qn = data.get("quote_number") or str(data.get("id") or "")
    if qn and not qn.startswith("Q-") and not qn.startswith("PROP-") and qn.isdigit():
        qn = f"Q-{int(qn):04d}"

    title = data.get("title") or "Commercial Quotation & Proposal"
    status = (data.get("status") or "Draft").strip()

    created_dt = data.get("created_at") or _dt.now()
    created_str = _format_pdf_date(created_dt)

    valid_until = data.get("valid_until")
    if valid_until:
        valid_str = _format_pdf_date(valid_until)
    else:
        try:
            base_dt = created_dt if isinstance(created_dt, _dt) else _dt.fromisoformat(str(created_dt)[:19])
            valid_str = (base_dt + _td(days=30)).strftime("%B %d, %Y")
        except Exception:
            valid_str = "30 Days from Issue"

    client_company = data.get("client_company") or data.get("client_name") or "Valued Client"
    client_name = data.get("client_name") or client_company
    client_email = data.get("client_email") or ""
    client_phone = data.get("client_phone") or ""
    client_address = data.get("client_address") or ""

    c_navy = colors.HexColor("#0f172a")
    c_blue = colors.HexColor("#1d4ed8")
    c_dark = colors.HexColor("#1e293b")
    c_text = colors.HexColor("#334155")
    c_muted = colors.HexColor("#64748b")
    c_card_bg = colors.HexColor("#f8fafc")
    c_card_border = colors.HexColor("#e2e8f0")
    c_accent_border = colors.HexColor("#93c5fd")

    st_upper = status.upper()
    if st_upper in ("ACCEPTED", "PAID", "APPROVED"):
        badge_fg = colors.HexColor("#15803d")
    elif st_upper in ("SENT", "PENDING", "IN REVIEW"):
        badge_fg = colors.HexColor("#1d4ed8")
    else:
        badge_fg = colors.HexColor("#b45309")

    def S(name, font="Helvetica", size=8.5, leading=11, color=c_text, bold=False, align=TA_LEFT):
        return ParagraphStyle(
            name,
            fontName="Helvetica-Bold" if bold else font,
            fontSize=size,
            leading=leading,
            textColor=color,
            alignment=align,
            spaceBefore=0,
            spaceAfter=0,
            wordWrap="CJK",
        )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=14 * mm,
        rightMargin=14 * mm,
        topMargin=10 * mm,
        bottomMargin=14 * mm,
        title=f"{company_name} — Quote {qn}",
        author=company_name,
    )
    story = []

    # ── HEADER BLOCK ──────────────────────────────────────────────────────────
    logo_path = "static/logo.png"
    logo_cell = None
    if os.path.exists(logo_path):
        try:
            logo_cell = Image(logo_path, width=36 * mm, height=18.5 * mm)
            logo_cell.hAlign = "LEFT"
        except Exception:
            logo_cell = None

    company_lines = [
        Paragraph(f"<b>{company_name}</b>", S("cName", font="Helvetica-Bold", size=14, leading=16, color=c_navy, bold=True)),
        Paragraph(f"<b>{legal_name}</b>", S("cLeg", size=8, leading=10, color=c_blue, bold=True)),
        Paragraph("Logistics Back-Office & Business Process Outsourcing (BPO)", S("cTag", size=7, leading=9, color=c_muted)),
        Paragraph(address_line, S("cAddr", size=7, leading=9, color=c_muted)),
        Paragraph(f"Tel: {contact_phone}  |  Email: {contact_email}  |  Web: {website}", S("cCont", size=7, leading=9, color=c_muted)),
    ]

    left_header = Table(
        [[logo_cell, Table([[p] for p in company_lines], colWidths=[68 * mm])]] if logo_cell else
        [[Table([[p] for p in company_lines], colWidths=[106 * mm])]],
        colWidths=[38 * mm, 68 * mm] if logo_cell else [106 * mm]
    )
    left_header.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))

    meta_box = [
        Paragraph("COMMERCIAL QUOTATION", S("qHead", font="Helvetica-Bold", size=12, leading=14, color=c_navy, bold=True, align=TA_RIGHT)),
        Paragraph(f"<font color='#0284c7'><b>#{qn}</b></font>", S("qNum", font="Helvetica-Bold", size=10, leading=12, align=TA_RIGHT)),
        Spacer(1, 1 * mm),
        Paragraph(f"<b>Date:</b> {created_str}", S("qD1", size=7.5, leading=9.5, color=c_text, align=TA_RIGHT)),
        Paragraph(f"<b>Valid Until:</b> {valid_str}", S("qD2", size=7.5, leading=9.5, color=c_text, align=TA_RIGHT)),
        Paragraph(f"<b>Currency:</b> {currency}", S("qD3", size=7.5, leading=9.5, color=c_text, align=TA_RIGHT)),
        Spacer(1, 1 * mm),
        Paragraph(f"<font color='{badge_fg.hexval()}'><b>[ STATUS: {st_upper} ]</b></font>", S("qSt", size=7.5, leading=9.5, bold=True, align=TA_RIGHT)),
    ]
    right_meta_table = Table([[p] for p in meta_box], colWidths=[72 * mm])
    right_meta_table.setStyle(TableStyle([
        ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
        ("LEFTPADDING", (0, 0), (-1, -1), 2.5 * mm),
        ("RIGHTPADDING", (0, 0), (-1, -1), 2.5 * mm),
        ("TOPPADDING", (0, 0), (-1, -1), 2 * mm),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2 * mm),
        ("BACKGROUND", (0, 0), (-1, -1), c_card_bg),
        ("BOX", (0, 0), (-1, -1), 0.5, c_card_border),
    ]))

    header_table = Table([[left_header, right_meta_table]], colWidths=[108 * mm, 74 * mm])
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 2.5 * mm))

    story.append(HRFlowable(width="100%", thickness=1.5, color=c_blue, spaceBefore=0, spaceAfter=1.5))
    story.append(HRFlowable(width="100%", thickness=0.5, color=c_card_border, spaceBefore=0, spaceAfter=2.5 * mm))

    # ── CLIENT & COMMERCIAL PARTIES ──────────────────────────────────────────
    bill_lines = [
        Paragraph("<b>PREPARED FOR / CLIENT DETAILS:</b>", S("bHead", size=7.5, leading=9.5, color=c_blue, bold=True)),
        Paragraph(f"<b>{client_company}</b>", S("bName", font="Helvetica-Bold", size=9.5, leading=11.5, color=c_navy, bold=True)),
    ]
    if client_email:
        bill_lines.append(Paragraph(f"<b>Email:</b> {client_email}", S("bEm", size=7.5, leading=9.5, color=c_text)))
    if client_phone:
        bill_lines.append(Paragraph(f"<b>Phone:</b> {client_phone}", S("bPh", size=7.5, leading=9.5, color=c_text)))
    if client_address:
        bill_lines.append(Paragraph(f"<b>Address:</b> {client_address}", S("bAd", size=7.5, leading=9.5, color=c_text)))
    bill_lines.append(Paragraph(f"<b>Project Scope:</b> {title}", S("bScope", size=7.5, leading=9.5, color=c_text)))

    prov_lines = [
        Paragraph("<b>ISSUED BY & COMMERCIAL DESK:</b>", S("pHead", size=7.5, leading=9.5, color=c_blue, bold=True)),
        Paragraph("<b>SCM BPO Commercial Operations</b>", S("pName", font="Helvetica-Bold", size=9.5, leading=11.5, color=c_navy, bold=True)),
        Paragraph(f"<b>Legal Entity:</b> {legal_name}", S("pLeg", size=7.5, leading=9.5, color=c_text)),
        Paragraph("<b>Representative:</b> Noushad C I (Founder & MD)", S("pRep", size=7.5, leading=9.5, color=c_text)),
        Paragraph(f"<b>Operations:</b> {contact_email}  |  24/7 Operations Desk", S("pOp", size=7.5, leading=9.5, color=c_text)),
        Paragraph("<b>Facility:</b> Koyenco Techpark, Infopark, Cochin, India", S("pFac", size=7.5, leading=9.5, color=c_text)),
    ]

    card_left = Table([[p] for p in bill_lines], colWidths=[88 * mm])
    card_left.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), c_card_bg),
        ("BOX", (0, 0), (-1, -1), 0.5, c_card_border),
        ("LEFTPADDING", (0, 0), (-1, -1), 2.5 * mm),
        ("RIGHTPADDING", (0, 0), (-1, -1), 2.5 * mm),
        ("TOPPADDING", (0, 0), (-1, -1), 2 * mm),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2 * mm),
    ]))

    card_right = Table([[p] for p in prov_lines], colWidths=[88 * mm])
    card_right.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), c_card_bg),
        ("BOX", (0, 0), (-1, -1), 0.5, c_card_border),
        ("LEFTPADDING", (0, 0), (-1, -1), 2.5 * mm),
        ("RIGHTPADDING", (0, 0), (-1, -1), 2.5 * mm),
        ("TOPPADDING", (0, 0), (-1, -1), 2 * mm),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2 * mm),
    ]))

    parties_table = Table([[card_left, card_right]], colWidths=[91 * mm, 91 * mm])
    parties_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(parties_table)
    story.append(Spacer(1, 2.5 * mm))

    # ── ITEMS TABLE ──────────────────────────────────────────────────────────
    items = data.get("items") or []
    grand_total = float(data.get("grand_total") or 0.0)

    if not items:
        svc_title = title if title and title != "—" else "Logistics Back-Office & Commercial Operations"
        items = [
            {
                "description": (
                    f"<b>{svc_title}</b><br/>"
                    f"<font color='#64748b' size='7'>"
                    f"• End-to-end shipment data processing, documentation and freight invoice verification<br/>"
                    f"• 24/7 dedicated dispatch operations coordination, tracking and milestone updates<br/>"
                    f"• Customs documentation compliance, manifest generation and carrier communications<br/>"
                    f"• Dedicated account supervisory workflow with 99.8% on-time turnaround SLA"
                    f"</font>"
                ),
                "unit": "Retainer Scope",
                "quantity": 1,
                "unit_price": grand_total,
                "total": grand_total,
            }
        ]

    col_widths = [8 * mm, 90 * mm, 24 * mm, 14 * mm, 23 * mm, 23 * mm]
    headers = ["#", "Deliverable & Scope of Work", "Service Unit", "Qty", f"Rate ({currency})", f"Amount ({currency})"]

    table_data = [[
        Paragraph(f"<b>{h}</b>", S(f"th_{i}", font="Helvetica-Bold", size=7.5, leading=9.5, color=colors.white, bold=True,
                                  align=TA_CENTER if i in (0, 3) else (TA_RIGHT if i in (4, 5) else TA_LEFT)))
        for i, h in enumerate(headers)
    ]]

    calc_subtotal = 0.0
    for idx, itm in enumerate(items, 1):
        desc = itm.get("description") or "Service Deliverable"
        unit_str = str(itm.get("unit") or "Scope")
        qty = float(itm.get("quantity") or 1)
        rate = float(itm.get("unit_price") or 0)
        tot = float(itm.get("total") or (qty * rate))
        calc_subtotal += tot

        table_data.append([
            Paragraph(f"<font color='#64748b'>{idx}</font>", S(f"td_idx_{idx}", size=7.5, leading=10, align=TA_CENTER)),
            Paragraph(desc, S(f"td_desc_{idx}", size=7.5, leading=10, color=c_navy)),
            Paragraph(f"<font color='#64748b'>{unit_str}</font>", S(f"td_u_{idx}", size=7, leading=9, align=TA_LEFT)),
            Paragraph(f"{qty:g}", S(f"td_q_{idx}", size=7.5, leading=10, align=TA_CENTER)),
            Paragraph(f"{curr_sym}{rate:,.2f}", S(f"td_r_{idx}", size=7.5, leading=10, align=TA_RIGHT)),
            Paragraph(f"<b>{curr_sym}{tot:,.2f}</b>", S(f"td_t_{idx}", font="Helvetica-Bold", size=7.5, leading=10, color=c_navy, bold=True, align=TA_RIGHT)),
        ])

    final_subtotal = float(data.get("subtotal") or calc_subtotal)
    tax_rate = float(data.get("tax_rate") or 0.0)
    tax_amt = final_subtotal * (tax_rate / 100.0) if tax_rate > 0 else 0.0
    discount = float(data.get("discount") or 0.0)
    final_grand = float(data.get("grand_total") or (final_subtotal - discount + tax_amt))

    item_table_style = [
        ("BACKGROUND", (0, 0), (-1, 0), c_dark),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, 0), 2 * mm),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 2 * mm),
        ("TOPPADDING", (0, 1), (-1, -1), 2 * mm),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 2 * mm),
        ("LEFTPADDING", (0, 0), (-1, -1), 1.5 * mm),
        ("RIGHTPADDING", (0, 0), (-1, -1), 1.5 * mm),
        ("LINEBELOW", (0, 0), (-1, 0), 1, c_blue),
    ]
    for r_idx in range(1, len(table_data)):
        bg = c_card_bg if r_idx % 2 == 0 else colors.white
        item_table_style.append(("BACKGROUND", (0, r_idx), (-1, r_idx), bg))
        item_table_style.append(("LINEBELOW", (0, r_idx), (-1, r_idx), 0.35, c_card_border))

    items_table = Table(table_data, colWidths=col_widths, repeatRows=1)
    items_table.setStyle(TableStyle(item_table_style))
    story.append(items_table)
    story.append(Spacer(1, 2 * mm))

    # ── TOTALS & WORDS ───────────────────────────────────────────────────────
    words = _number_to_words(final_grand)
    words_str = f"{words} {currency} Only" if words else ""

    words_cell = [
        Paragraph("<b>AMOUNT IN WORDS:</b>", S("wH", size=7, leading=9, color=c_muted, bold=True)),
        Paragraph(f"<i>{words_str}</i>", S("wVal", font="Helvetica-Bold", size=8, leading=10, color=c_navy, bold=True)),
        Spacer(1, 1 * mm),
        Paragraph("<b>TAX STATUS:</b> 0% Export of BPO Support Services / Reverse Charge Applicable",
                  S("wTax", size=6.5, leading=8.5, color=c_muted)),
    ]
    words_table = Table([[p] for p in words_cell], colWidths=[96 * mm])
    words_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), c_card_bg),
        ("BOX", (0, 0), (-1, -1), 0.5, c_card_border),
        ("LEFTPADDING", (0, 0), (-1, -1), 2.5 * mm),
        ("RIGHTPADDING", (0, 0), (-1, -1), 2.5 * mm),
        ("TOPPADDING", (0, 0), (-1, -1), 1.5 * mm),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 1.5 * mm),
    ]))

    tot_rows = [
        [Paragraph("Subtotal", S("sL", size=7.5, leading=9.5, color=c_muted, align=TA_RIGHT)),
         Paragraph(f"{curr_sym}{final_subtotal:,.2f}", S("sV", size=7.5, leading=9.5, color=c_navy, align=TA_RIGHT))],
    ]
    if discount > 0:
        tot_rows.append([
            Paragraph("Discount", S("dL", size=7.5, leading=9.5, color=colors.HexColor("#dc2626"), align=TA_RIGHT)),
            Paragraph(f"-{curr_sym}{discount:,.2f}", S("dV", size=7.5, leading=9.5, color=colors.HexColor("#dc2626"), align=TA_RIGHT))
        ])
    tot_rows.append([
        Paragraph("Taxes (0% Export)", S("tL0", size=7, leading=9, color=c_muted, align=TA_RIGHT)),
        Paragraph(f"{curr_sym}0.00", S("tV0", size=7, leading=9, color=c_muted, align=TA_RIGHT))
    ])
    tot_rows.append([
        Paragraph("<b>TOTAL CONTRACT VALUE</b>", S("gL", font="Helvetica-Bold", size=8.5, leading=10.5, color=c_navy, bold=True, align=TA_RIGHT)),
        Paragraph(f"<b>{curr_sym}{final_grand:,.2f} {currency}</b>", S("gV", font="Helvetica-Bold", size=9.5, leading=11.5, color=c_blue, bold=True, align=TA_RIGHT))
    ])

    tot_table = Table(tot_rows, colWidths=[46 * mm, 36 * mm])
    tot_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 1 * mm),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 1 * mm),
        ("LEFTPADDING", (0, 0), (-1, -1), 1 * mm),
        ("RIGHTPADDING", (0, 0), (-1, -1), 1 * mm),
        ("LINEABOVE", (0, -1), (-1, -1), 1, c_blue),
        ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#eff6ff")),
        ("BOX", (0, -1), (-1, -1), 0.75, c_accent_border),
    ]))

    calc_wrapper = Table([[words_table, tot_table]], colWidths=[98 * mm, 84 * mm])
    calc_wrapper.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(calc_wrapper)
    story.append(Spacer(1, 2.5 * mm))

    # ── CAPABILITIES ─────────────────────────────────────────────────────────
    cap_data = [
        [
            Paragraph("<b>⚡ 99.8% On-Time Turnaround</b><br/><font color='#64748b' size='6.5'>Rigorous SLA adherence for shipment manifests, billing audits & customs data entries.</font>", S("cap1", size=7, leading=8.5)),
            Paragraph("<b>🔒 Enterprise Data Security</b><br/><font color='#64748b' size='6.5'>Strict NDA, ISO 27001 data security compliance and encrypted client portal infrastructure.</font>", S("cap2", size=7, leading=8.5)),
            Paragraph("<b>👥 Dedicated Operations Pod</b><br/><font color='#64748b' size='6.5'>Fully trained logistics specialists and account supervisors dedicated to your pipeline.</font>", S("cap3", size=7, leading=8.5)),
        ]
    ]
    cap_table = Table(cap_data, colWidths=[60 * mm, 61 * mm, 61 * mm])
    cap_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f1f5f9")),
        ("BOX", (0, 0), (-1, -1), 0.5, c_card_border),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 2 * mm),
        ("RIGHTPADDING", (0, 0), (-1, -1), 2 * mm),
        ("TOPPADDING", (0, 0), (-1, -1), 1.5 * mm),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 1.5 * mm),
        ("LINEBEFORE", (1, 0), (1, -1), 0.5, c_card_border),
        ("LINEBEFORE", (2, 0), (2, -1), 0.5, c_card_border),
    ]))
    story.append(cap_table)
    story.append(Spacer(1, 2.5 * mm))

    # ── TERMS & BANKING ──────────────────────────────────────────────────────
    p_terms = data.get("payment_terms") or "Net 30 days upon formal invoice issuance via Bank Wire Transfer."
    c_notes = data.get("notes") or ""
    
    terms_content = [
        Paragraph("<b>COMMERCIAL TERMS & PAYMENT INSTRUCTIONS:</b>", S("tHead", size=7.5, leading=9.5, color=c_blue, bold=True)),
        Paragraph(f"• <b>Payment Terms:</b> {p_terms}", S("t1", size=7, leading=8.5, color=c_text)),
        Paragraph("• <b>Remittance Partner:</b> Direct Wire / ACH to Beneficiary: <b>SCM SHIPPING SERVICES PVT LTD</b>.", S("t2", size=7, leading=8.5, color=c_text)),
        Paragraph("• <b>Banking Coordinates:</b> Full SWIFT/IFSC & Account details are specified on official tax invoices.", S("t3", size=7, leading=8.5, color=c_text)),
        Paragraph("• <b>Governing Agreement:</b> SCM BPO Standard Master Services Terms & Operational SLAs apply.", S("t4", size=7, leading=8.5, color=c_text)),
    ]
    if c_notes and c_notes.strip():
        terms_content.append(Spacer(1, 0.5 * mm))
        terms_content.append(Paragraph(f"• <b>Client Notes & Specifications:</b> {c_notes.strip()}", S("tNotes", size=7, leading=8.5, color=c_text)))

    terms_box = Table([[p] for p in terms_content], colWidths=[182 * mm])
    terms_box.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), c_card_bg),
        ("BOX", (0, 0), (-1, -1), 0.5, c_card_border),
        ("LEFTPADDING", (0, 0), (-1, -1), 2.5 * mm),
        ("RIGHTPADDING", (0, 0), (-1, -1), 2.5 * mm),
        ("TOPPADDING", (0, 0), (-1, -1), 1.5 * mm),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 1.5 * mm),
    ]))
    story.append(terms_box)
    story.append(Spacer(1, 2.5 * mm))

    # ── SIGNATURES ───────────────────────────────────────────────────────────
    signed_at = data.get("signed_at")
    
    left_sign = [
        Paragraph("<b>AUTHORIZED SIGNATORY (SCM BPO)</b>", S("sHeadL", size=7.5, leading=9.5, color=c_blue, bold=True)),
        Spacer(1, 1 * mm),
        Paragraph("<b>Noushad C I</b>", S("sNameL", font="Helvetica-Bold", size=8.5, leading=10.5, color=c_navy, bold=True)),
        Paragraph("Founder & Managing Director", S("sRoleL", size=7, leading=8.5, color=c_muted)),
        Paragraph(legal_name, S("sLegL", size=7, leading=8.5, color=c_muted)),
        Spacer(1, 1 * mm),
        Paragraph("<font color='#059669'><b>[ SEALED & DIGITALLY VERIFIED BY SCM BPO ]</b></font>", S("sSeal", size=6.5, leading=8.5, bold=True)),
    ]
    sign_box_left = Table([[p] for p in left_sign], colWidths=[88 * mm])
    sign_box_left.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), c_card_bg),
        ("BOX", (0, 0), (-1, -1), 0.5, c_card_border),
        ("LEFTPADDING", (0, 0), (-1, -1), 2.5 * mm),
        ("RIGHTPADDING", (0, 0), (-1, -1), 2.5 * mm),
        ("TOPPADDING", (0, 0), (-1, -1), 2 * mm),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2 * mm),
    ]))

    if signed_at or st_upper in ("ACCEPTED", "APPROVED"):
        signed_date_str = _format_pdf_date(signed_at) if signed_at else created_str
        right_sign = [
            Paragraph("<b>CLIENT ACCEPTANCE & APPROVAL</b>", S("sHeadR", size=7.5, leading=9.5, color=colors.HexColor("#15803d"), bold=True)),
            Spacer(1, 1 * mm),
            Paragraph("<b>✓ DIGITALLY ACCEPTED & CONFIRMED</b>", S("sAccR", font="Helvetica-Bold", size=8.5, leading=10.5, color=colors.HexColor("#15803d"), bold=True)),
            Paragraph(f"<b>Authorized For:</b> {client_company}", S("sCliR", size=7, leading=8.5, color=c_navy)),
            Paragraph(f"<b>Execution Timestamp:</b> {signed_date_str}", S("sDateR", size=7, leading=8.5, color=c_muted)),
            Paragraph("<b>Verification:</b> Authenticated via SCM BPO Secure Client Portal", S("sVerR", size=6.5, leading=8.5, color=c_muted)),
        ]
        sign_box_right = Table([[p] for p in right_sign], colWidths=[88 * mm])
        sign_box_right.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f0fdf4")),
            ("BOX", (0, 0), (-1, -1), 0.75, colors.HexColor("#86efac")),
            ("LEFTPADDING", (0, 0), (-1, -1), 2.5 * mm),
            ("RIGHTPADDING", (0, 0), (-1, -1), 2.5 * mm),
            ("TOPPADDING", (0, 0), (-1, -1), 2 * mm),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2 * mm),
        ]))
    else:
        right_sign = [
            Paragraph("<b>CLIENT ACCEPTANCE & AUTHORIZATION</b>", S("sHeadR", size=7.5, leading=9.5, color=c_blue, bold=True)),
            Spacer(1, 1 * mm),
            Paragraph("Authorized Signature: ____________________________", S("sLine1", size=7.5, leading=10, color=c_muted)),
            Paragraph("Name & Title: _________________________________", S("sLine2", size=7.5, leading=10, color=c_muted)),
            Paragraph(f"Organization: <b>{client_company}</b>", S("sLine3", size=7, leading=9, color=c_text)),
            Paragraph("Date of Signing: _______________________________", S("sLine4", size=7.5, leading=10, color=c_muted)),
        ]
        sign_box_right = Table([[p] for p in right_sign], colWidths=[88 * mm])
        sign_box_right.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), c_card_bg),
            ("BOX", (0, 0), (-1, -1), 0.5, c_card_border),
            ("LEFTPADDING", (0, 0), (-1, -1), 2.5 * mm),
            ("RIGHTPADDING", (0, 0), (-1, -1), 2.5 * mm),
            ("TOPPADDING", (0, 0), (-1, -1), 2 * mm),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2 * mm),
        ]))

    sign_wrapper = Table([[sign_box_left, sign_box_right]], colWidths=[91 * mm, 91 * mm])
    sign_wrapper.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(sign_wrapper)

    doc.build(story, canvasmaker=_QuoteCanvas)
    return buf.getvalue()


def invoice_pdf(data):
    """Generate a SERPHAWK-minimal invoice PDF (A4 portrait).

    ``data`` is a dict with keys:
        invoice_number, client_name, currency (default "$"),
        amount, tax, total, status, due_date, notes,
        line_items: [ { description, amount, provider } ]
    """
    from datetime import datetime as _dt

    company = "SCM BPO"
    currency = str(data.get("currency") or "$")
    subtitle = "Invoice"
    inv_num = data.get("invoice_number") or str(data.get("id") or "")
    created = data.get("created_at") or ""
    if hasattr(created, "strftime"):
        created = _spanish_datetime(created)
    elif isinstance(created, str) and created:
        pass
    else:
        created = _spanish_datetime(_dt.now())

    line_items = data.get("line_items") or []

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=15 * mm, rightMargin=15 * mm,
        topMargin=14 * mm, bottomMargin=16 * mm,
        title=f"{company} — Invoice {inv_num}",
        author=company,
    )

    def cell(fs=9, ls=12, color=_RECEIPT_INK, align=TA_LEFT, bold=False, wrap=True):
        return ParagraphStyle(
            "ip", fontName="Helvetica-Bold" if bold else "Helvetica",
            fontSize=fs, leading=ls, textColor=color, alignment=align,
            spaceBefore=0, spaceAfter=0, wordWrap="CJK" if wrap else None,
        )

    story = []

    # ── Header ───────────────────────────────────────────────────────────
    meta_lines = []
    if inv_num:
        meta_lines.append(("Invoice:", inv_num))
    if created:
        meta_lines.append(("Date:", str(created)))
    if data.get("due_date"):
        meta_lines.append(("Due:", data["due_date"]))
    if data.get("client_name"):
        meta_lines.append(("Bill To:", data["client_name"]))
    story += _serphawk_header(company, meta_lines if meta_lines else None, subtitle=subtitle)

    # ── Client / status info ─────────────────────────────────────────────
    P = Paragraph
    
    from_lines = [
        P("SCM SHIPPING SERVICES PVT LTD", cell(11, 14, _RECEIPT_INK, bold=True, wrap=True)),
        P("Koyenco Techpark, Kepip, Infopark P.O.,", cell(8.5, 12, _RECEIPT_SUBTLE)),
        P("Kakkanad, Cochin", cell(8.5, 12, _RECEIPT_SUBTLE)),
        P("<b>Phone:</b> +91-9947950099", cell(8.5, 12, _RECEIPT_SUBTLE)),
        P("<b>Email:</b> contact@scmbpo.com", cell(8.5, 12, _RECEIPT_SUBTLE)),
        P("<b>Web:</b> www.scmbpo.com", cell(8.5, 12, _RECEIPT_SUBTLE)),
    ]
    
    bill_lines = []
    if data.get("client_name"):
        bill_lines.append(P(data["client_name"], cell(11, 14, _RECEIPT_INK, bold=True, wrap=True)))
    if data.get("status"):
        bill_lines.append(P(f"<b>Status:</b> {data['status']}", cell(9, 12, _RECEIPT_INK)))
    if data.get("due_date"):
        bill_lines.append(P(f"<b>Due Date:</b> {data['due_date']}", cell(9, 12, _RECEIPT_INK)))

    bill_heading = Table([[P("BILL TO", cell(7.5, 9, _RECEIPT_FAINT, bold=True))]], colWidths=[90 * mm])
    from_heading = Table([[P("FROM", cell(7.5, 9, _RECEIPT_FAINT, bold=True))]], colWidths=[90 * mm])
    
    pad_style = TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ])
    bill_heading.setStyle(pad_style)
    from_heading.setStyle(pad_style)

    info_cell = Table([[p] for p in bill_lines], colWidths=[None])
    info_cell.setStyle(TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    
    from_cell = Table([[p] for p in from_lines], colWidths=[None])
    from_cell.setStyle(TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))

    info_table = Table([[from_heading, bill_heading], [from_cell, info_cell]], colWidths=[90 * mm, 90 * mm], style=TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 5 * mm))

    # ── Line items table ─────────────────────────────────────────────────
    headers = ["#", "Description", "Provider", "Amount"]
    col_w = [12 * mm, 112 * mm, 28 * mm, 28 * mm]
    data_rows = [
        [Paragraph(h, cell(7.5, 10, _RECEIPT_SUBTLE, TA_LEFT, bold=True)) for h in headers]
    ]
    for idx, li in enumerate(line_items, 1):
        amt = float(li.get("amount", 0))
        prov = li.get("provider", "")
        desc = li.get("description", "")
        data_rows.append([
            Paragraph(str(idx), cell(8.5, 11, _RECEIPT_FAINT, TA_CENTER)),
            Paragraph(str(desc), cell(9, 12, _RECEIPT_INK, TA_LEFT)),
            Paragraph(str(prov), cell(8.5, 11, _RECEIPT_SUBTLE, TA_LEFT)),
            Paragraph(f"{currency}{amt:.2f}", cell(8.5, 11, _RECEIPT_INK, TA_RIGHT)),
        ])

    if not line_items:
        data_rows.append([
            Paragraph("—", cell(9, 12, _RECEIPT_FAINT, TA_CENTER)),
            Paragraph("No line items", cell(9, 12, _RECEIPT_FAINT)),
            Paragraph("—", cell(9, 12, _RECEIPT_FAINT)),
            Paragraph("—", cell(9, 12, _RECEIPT_FAINT)),
        ])

    item_style = [
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 2),
        ("RIGHTPADDING", (0, 0), (-1, -1), 2),
        ("TOPPADDING", (0, 0), (-1, 0), 0),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 4),
        ("TOPPADDING", (0, 1), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 5),
        ("LINEBELOW", (0, 0), (-1, 0), 0.6, _RECEIPT_LINE),
    ]
    for idx in range(1, len(data_rows)):
        item_style.append(("LINEBELOW", (0, idx), (-1, idx), 0.5, _RECEIPT_LINE))

    items_table = Table(data_rows, colWidths=col_w, repeatRows=1)
    items_table.setStyle(TableStyle(item_style))
    story.append(items_table)
    story.append(Spacer(1, 6 * mm))

    # ── Totals ───────────────────────────────────────────────────────────
    amount = float(data.get("amount") or 0)
    tax = float(data.get("tax") or 0)
    total = float(data.get("total") or (amount + tax))

    totals_rows = [
        ["", Paragraph("Subtotal", cell(9, 12, _RECEIPT_INK, TA_RIGHT)),
         Paragraph(_receipt_money(amount, currency), cell(9, 12, _RECEIPT_INK, TA_RIGHT))],
    ]
    if tax > 0:
        totals_rows.append([
            "", Paragraph("Tax", cell(9, 12, _RECEIPT_SUBTLE, TA_RIGHT)),
            Paragraph(_receipt_money(tax, currency), cell(9, 12, _RECEIPT_SUBTLE, TA_RIGHT)),
        ])
    totals_rows.append([
        "", Paragraph("Total", cell(11, 14, _RECEIPT_INK, TA_RIGHT, bold=True)),
        Paragraph(_receipt_money(total, currency), cell(11, 14, _RECEIPT_INK, TA_RIGHT, bold=True)),
    ])

    totals_table = Table(totals_rows, colWidths=[92 * mm, 40 * mm, 48 * mm])
    totals_style = [
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, 0), 0.6, _RECEIPT_LINE),
        ("LINEBELOW", (0, -1), (-1, -1), 0.6, _RECEIPT_LINE),
        ("TOPPADDING", (0, -1), (-1, -1), 5),
        ("BOTTOMPADDING", (0, -1), (-1, -1), 5),
    ]
    totals_table.setStyle(TableStyle(totals_style))
    story.append(KeepTogether([totals_table]))

    # ── Notes ────────────────────────────────────────────────────────────
    notes = data.get("notes") or ""
    if notes:
        story.append(Spacer(1, 8 * mm))
        story.append(HRFlowable(width="100%", thickness=0.5, color=_RECEIPT_LINE))
        story.append(Spacer(1, 4 * mm))
        story.append(Paragraph("Notes", cell(9, 12, _RECEIPT_INK, bold=True)))
        story.append(Spacer(1, 2 * mm))
        story.append(Paragraph(notes, cell(8.5, 11, _RECEIPT_SUBTLE)))

    # ── Footer (later pages only) ────────────────────────────────────────
    def _i_footer(canvas, _doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(_RECEIPT_FAINT)
        canvas.drawRightString(A4[0] - 15 * mm, 9 * mm, f"Invoice {inv_num} · Página {_doc.page}")
        canvas.restoreState()

    doc.build(story, onFirstPage=lambda c, d: None, onLaterPages=_i_footer)
    return buf.getvalue()